### ISSUE TITLE
Docker compose and prometheus config 

### ISSUE THREAD

**Issue by svenvg93** [bartlettc22/speedtest-exporter#1]
Awesome looking exporter! 
Do you same documentation in using this in Docker compose with a prometheus config :).

**Comment by bartlettc22** [comment]
Thanks, I appreciate the feedback.  I just added Docker compose and Prometheus config examples to the [README](https://github.com/bartlettc22/speedtest-exporter).  I hope this helps!

**Comment by svenvg93** [comment]
Definitely does thanks!

**Comment by svenvg93** [comment]
more question, is it possible to set the server id somewhere. So the test will run against a specific server.

also if the scrape is every 30 seconds. The results won’t change as the interval is 3600 seconds right?
